## Google earth engine download

generally followed setup here: 

https://courses.spatialthoughts.com/install-gee-python-api.html

In [2]:
import ee
import geemap

In [3]:
ee.Authenticate()


Successfully saved authorization token.


In [4]:
ee.Initialize(project='ee-cehanagan')

## Sentinel 2 Band 4

In [6]:
import ee
import geopandas as gpd

# Initialize Earth Engine
ee.Initialize()

# Load GeoJSON polygon (your AOI)
gdf = gpd.read_file("/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/AOI20250729Kamchatka.geojson")

# Extract coordinates from the first feature (ensure it's a Polygon, not MultiPolygon)
polygon_coords = gdf.geometry[0].__geo_interface__['coordinates'][0]
polygon = ee.Geometry.Polygon(polygon_coords)

# Define time range
start_date = '2025-07-19' 
end_date = '2025-07-21' 
start_date = '2025-08-03' 
end_date = '2025-08-05' 
band = 4

# Filter Sentinel-2 collection
image = (
    ee.ImageCollection('COPERNICUS/S2_HARMONIZED')
    .filterBounds(polygon)
    .filterDate(start_date, end_date)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 100))
    .select(f'B{band}')
    .median()
    .clip(polygon)
)

# Export parameters
task = ee.batch.Export.image.toDrive(
    image=image,
    description=f'Sentinel2_B{band}_Export',
    folder='EarthEngineExports',  # Appears in your Google Drive
    fileNamePrefix=f'sentinel2_band{band}_{start_date}_{end_date}',
    region=polygon,
    scale=10,  # Sentinel-2 Band 4 native resolution
    crs='EPSG:32657',  # Example: UTM Zone 47N (Myanmar region)
    maxPixels=1e13
)

# Start export
task.start()
print('Export started. Monitor progress at https://code.earthengine.google.com/tasks')


Export started. Monitor progress at https://code.earthengine.google.com/tasks


In [8]:
!gdalwarp -tr 10 10 -dstnodata -9999 -of GTiff -t_srs EPSG:32657 -co COMPRESS=LZW -co ZLEVEL=9 -co BIGTIFF=YES -overwrite /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/sentinel2_band4_2025-07-19_2025-07-21.tif /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/mmsentinel2_band4_2025-07-19_2025-07-21.tif

Creating output file that is 7094P x 11471L.
Processing /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/sentinel2_band4_2025-07-19_2025-07-21.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.


In [ ]:
%%bash
## Sentinel from GEE, Example of merging the results for Myanmar
gdalwarp -t_srs EPSG:32647 -tr 10 10 -srcnodata 0 -dstnodata 0 -overwrite -of GTiff -co COMPRESS=LZW -co ZLEVEL=9 -co BIGTIFF=YES \
    /Volumes/Myanmar\ 1/Imagery/Sentinel/EarthEngineExportsPost/*tif \
    /Volumes/Myanmar\ 1/Imagery/Sentinel/EarthEngineExportsPost/S2_20250330_20250401_B04_merge.tif

## Other

In [ ]:
S2B_MSIL2A_20230125T082129_N0510_R121_T37SCC_20240810T144140.SAFE

S2B_MSIL2A_20230415T081609_N0510_R121_T37SCC_20240826T161033.SAFE

In [2]:
import ee
import geopandas as gpd

# Initialize Earth Engine
ee.Initialize()

# Load GeoJSON polygon (your AOI) in EPSG:4326
gdf = gpd.read_file("/Users/chanagan/Downloads/TurkeyAOI8.10.25.geojson")

# Extract coordinates from the first feature (ensure it's a Polygon, not MultiPolygon)
polygon_coords = gdf.geometry[0].__geo_interface__['coordinates'][0]
polygon = ee.Geometry.Polygon(polygon_coords)

# Define time range
start_date = '2025-08-10'
end_date = '2025-08-12'
band = 4

# Filter Sentinel-2 collection
image = (
    ee.ImageCollection('COPERNICUS/S2_HARMONIZED')
    .filterBounds(polygon)
    .filterDate(start_date, end_date)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 100))
    .select(f'B{band}')
    .median()
    .clip(polygon)
)

# Export parameters
task = ee.batch.Export.image.toDrive(
    image=image,
    description=f'Sentinel2_B{band}_Export',
    folder='EarthEngineExports',  # Appears in your Google Drive
    fileNamePrefix=f'sentinel2_band{band}_{start_date}_{end_date}',
    region=polygon,
    scale=10,  # Sentinel-2 Band 4 native resolution
    crs='EPSG:32635',  # Example: UTM Zone 
    maxPixels=1e13
)

# Start export
task.start()
print('Export started. Monitor progress at https://code.earthengine.google.com/tasks')


Export started. Monitor progress at https://code.earthengine.google.com/tasks


In [ ]:
mm3d Mm2dPosSism sentinel2_band4_2025-08-07_2025-08-09.tif sentinel2_band4_2025-08-10_2025-08-12.tif CorMin=0.1 SsResolOpt=1 Dequant=false DirMEC='MEC/'

In [1]:
import sys
sys.path.append('/Users/chanagan/Documents/GitHub/ImageryResources/Functions/')
import TiffTools as tt

In [3]:
!gdalinfo /Users/chanagan/Downloads/sentinel2_band4_2025-08-10_2025-08-12.tif

Driver: GTiff/GeoTIFF
Files: /Users/chanagan/Downloads/sentinel2_band4_2025-08-10_2025-08-12.tif
       /Users/chanagan/Downloads/sentinel2_band4_2025-08-10_2025-08-12.tif.aux.xml
Size is 2553, 2931
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 35N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 35N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",27,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID

In [10]:
tt.micmacPostProcessing(folder='/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/',
                         prefiles=['/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/mmsentinel2_band4_2025-08-03_2025-08-05.tif',
                                   '/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/mmsentinel2_band4_2025-07-19_2025-07-21.tif'],
                         outprefix='/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/')

Nodata value for mask: -9999.0
Setting nodata value to -9999
Saving /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/NSmicmac.tif
Saving /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/EWmicmac.tif
Saving /Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/Correlmicmac.tif


In [12]:
import rioxarray
import numpy as np

In [18]:
mask

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]],
      shape=(1, 11471, 7094))

In [30]:
corr = rioxarray.open_rasterio('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/Correlmicmac.tif')
ns = rioxarray.open_rasterio('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/NSmicmac.tif')
ew = rioxarray.open_rasterio('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/EWmicmac.tif')

mask = (corr.data<0.5)
# Set nodata value explicitly
ns.rio.write_nodata(-9999, inplace=True)
ew.rio.write_nodata(-9999, inplace=True)

# Apply the mask
ns.data[mask] = -9999
ew.data[mask] = -9999

# Save masked rasters
ns.rio.to_raster('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/NSmicmac-masked.tif')
ew.rio.to_raster('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/EWmicmac-masked.tif')

In [31]:
tt.projectDisp('/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/EWmicmac-masked.tif',
               '/Users/chanagan/Library/CloudStorage/OneDrive-DOI/Desktop/EarthquakesSentinel/KamchatkaTest/MEC/NSmicmac-masked.tif',
               -25,mask=None,partif='ParallelDisp.tif',perptif='PerpendicularDisp.tif')


(array([[-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        ...,
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.]],
       shape=(11471, 7094)),
 array([[-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        ...,
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
        [-9999., -9999., -9999., ..., -9999., -9999., -9999.]],
       shape=(11471, 7094)))

In [9]:
tt.verticalDispBilin(dem1file='/Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/sd_arcata_2009_dem.tif',
                         dem2file='/Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/sd_arcata_2019_dem.tif',
                         nsfile=f'/Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/MEC/NSmicmac.tif',
                         ewfile=f'/Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/MEC/EWmicmac.tif',
                         outf=f'/Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/MEC/UDmicmac.tif')

Raster shapes: (3979, 3385) (3979, 3385) (3979, 3385) (3979, 3385)
Saved vertical displacement to: /Users/chanagan/Library/CloudStorage/OneDrive-DOI/ToShare/ArcataLidarExploration/OpenTopoPCs/MEC/UDmicmac.tif


array([[-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       ...,
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.]],
      shape=(3979, 3385), dtype=float32)